version: "3.9"

services:
  api-vise:
    build: .
    container_name: api-vise
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
